blank_issues_enabled: true
contact_links:
  - name: Kotlin API for GitHub Discussions
    url: https://github.com/mjovanc/github-api/discussions
    about: Please ask and answer usage-related questions here.